version: '2.0'
services:
  gateway: 
    # Implement auth enforcement + bearer token passing
    build: ./gateway
    volumes:
      - ./.docker/certs:/etc/nginx/certs
      - ./gateway/templates:/etc/nginx/templates
    environment:
      - APP_CERT_FILE="/etc/nginx/certs/selfsigned.app.crt"
      - APP_CERT_KEY_FILE="/etc/nginx/certs/selfsigned.app.key"
      - APP_SERVER_NAME="coffeetable.app"
      - APP_SERVER_HOST=webapp
      - AUTH_CERT_FILE="/etc/nginx/certs/selfsigned.auth.crt"
      - AUTH_CERT_KEY_FILE="/etc/nginx/certs/selfsigned.auth.key"
      - AUTH_SERVER_NAME="auth.coffeetable.app"
      - AUTH_SERVER_ADDRESS="keycloak:8080"
      - MEDIA_CERT_FILE="/etc/nginx/certs/selfsigned.media.crt"
      - MEDIA_CERT_KEY_FILE="/etc/nginx/certs/selfsigned.media.key"
      - MEDIA_SERVER_NAME="media.coffeetable.app"
      - MEDIA_SERVER_HOST="media"
    networks:
      coffeetable:
        aliases: 
          - coffeetable.app
          - auth.coffeetable.app
          - media.coffeetable.app
    ports: 
      - "80:80"
      - "443:443"

  keycloak:
    image: jboss/keycloak
    command: ["-b", "0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config", "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING", "-Dkeycloak.profile.feature.upload_scripts=enabled"]
    volumes: 
      - ./.docker/realm-config:/opt/jboss/keycloak/realm-config
    environment:
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    networks:
      coffeetable:
  
  spa:
    build: ./spa
    volumes: 
      - /single-page-app-build:/usr/src/app/build

  webapp:
    build: ./webapp
    volumes:
      - /single-page-app-build:/var/www/coffeetable.app
      - ./.docker/certs:/etc/nginx/certs
      - ./webapp/templates:/etc/nginx/templates
      - ./webapp/src:/opt/coffeetable
    environment:
      - APP_ROOT="/opt/coffeetable"
      - APP_SERVER_NAME="coffeetable.app"
      - AUTH_CERT_FILE="/etc/nginx/certs/selfsigned.auth.crt"
      - AUTH_CERT_KEY_FILE="/etc/nginx/certs/selfsigned.auth.key"
      - OIDC_DISCOVERY_URL="https://auth.coffeetable.app/auth/realms/Family/.well-known/openid-configuration"
      - OIDC_CLIENT_ID="coffeetable"
      - OIDC_CLIENT_SECRET="a9ee35e3-0334-41de-b348-7b55780d9e09"
    networks:
      coffeetable:

  media:
    image: nginx  
    networks:
      coffeetable:

volumes: 
  single-page-app-build:

networks: 
  coffeetable:
