version: '2.0'
services:
  keycloak:
    image: jboss/keycloak
    command: ["-b", "0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config", "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING", "-Dkeycloak.profile.feature.upload_scripts=enabled"]
    volumes: 
      - ./.docker/realm-config:/opt/jboss/keycloak/realm-config
    environment:
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
  frontend:
    build: ./frontend
    volumes: 
      - /frontend-app-build:/usr/src/app/build
  backend:
    build: ./backend
    depends_on:
      - keycloak
    volumes:
      - /frontend-app-build:/var/www/coffeetable.app
      - ./.docker/certs:/etc/nginx/certs
      - ./backend/templates:/etc/nginx/templates
      - ./backend/src:/opt/coffeetable
    environment:
      - APP_ROOT="/opt/coffeetable"
      - APP_CERT_FILE="/etc/nginx/certs/selfsigned.app.crt"
      - APP_CERT_KEY_FILE="/etc/nginx/certs/selfsigned.app.key"
      - APP_SERVER_NAME="coffeetable.app"
      - AUTH_CERT_FILE="/etc/nginx/certs/selfsigned.auth.crt"
      - AUTH_CERT_KEY_FILE="/etc/nginx/certs/selfsigned.auth.key"
      - AUTH_SERVER_NAME="auth.coffeetable.app"
      - MEDIA_CERT_FILE="/etc/nginx/certs/selfsigned.media.crt"
      - MEDIA_CERT_KEY_FILE="/etc/nginx/certs/selfsigned.media.key"
      - MEDIA_SERVER_NAME="media.coffeetable.app"
      - MEDIA_ROOT="/media"
      - KEYCLOAK_ADDRESS="keycloak:8080"
      - OIDC_DISCOVERY_URL="https://auth.coffeetable.app/auth/realms/Family/.well-known/openid-configuration"
      - OIDC_CLIENT_ID="coffeetable"
      - OIDC_CLIENT_SECRET="a9ee35e3-0334-41de-b348-7b55780d9e09"
    networks:
      default:
        aliases: 
          - coffeetable.app
          - auth.coffeetable.app
          - media.coffeetable.app
    ports: 
      - "80:80"
      - "443:443"
  
volumes: 
  frontend-app-build: